### ISSUE TITLE
Restore toSlateOps and applySlateOps in 2.0.0

### ISSUE THREAD

**Issue by tmathew0309** [BitPhinix/slate-yjs#202]
Hi @BitPhinix is it possible to still keep around the toSlateOps and applySlateOps functions in 2.0.0? I use this library but have a different plugin system and need to convert / apply slate ops myself. Does the new design still allow you to extract out these functions?

**Comment by BitPhinix** [comment]
Hi @tmathew0309,

Would exposing https://github.com/BitPhinix/slate-yjs/blob/1c865940037a5aa96ed52631a13588fdabd0dd8e/src/applyToYjs/index.ts#L42 and https://github.com/BitPhinix/slate-yjs/blob/1c865940037a5aa96ed52631a13588fdabd0dd8e/src/applyToSlate/index.ts#L33 help in your use case? I've removed the "plain" op conversion because it results in "incomplete" ops (missing fields for the history)

**Comment by tmathew0309** [comment]
exposing `applySlateOps` would certainly help. Unfortunately I can't use `applyYjsEvents` as is because our current code is designed to keep a level of abstraction between the editor and the collaborative websocket. Basically our collaboration api just exposes an interface to send "local" slate operations and receive "remote" slate operations. It tries to hide away any details of the underlying CRDT mechanism used and converts those operations to/from other operations as necessary. In our case we started out using an Automerge implementation using https://github.com/cudr/slate-collaborative and was able to pretty easily switch it out for slate-yjs 1.0 because both libraries let me convert between slate operations <-> specific CRDT operations. But unable to upgrade to 2.0 now. 

Is it impossible to convert slate ops to yjs ops in a "complete" way?

**Comment by BitPhinix** [comment]
It definitely is possible, but it requires some more work. I'm really busy at the moment but will get back to adding this functionality in the future. In the meantime, you can definitely still use slate-yjs 1.0, but you have to keep in mind that it isn't compatible with the latest YJs version due to changes in the event delta (https://github.com/BitPhinix/slate-yjs/issues/188)
