### ISSUE TITLE
Operations are being applied twice

### ISSUE THREAD

**Issue by chasefarmer2808** [BitPhinix/slate-yjs#248]
When a character is typed into the editor, there are checks in place to determine whether that insertion was done by the local client or a remote one.  This is so the sharedType observeDeep listener does not apply a change to a local client that the same local client just made.  However, in version 2 or greater, I am seeing this exact issue happening.  After a little investigation, I've verified that if-statements in the `sharedType.observeDeep` callback and `e.onChange` callback within the yjsEditor.ts file are both evaluating to true.  This leads me to believe there is a bug with the new `WEAK_MAP` implementation of this solution.

I will investigate further to try and find a fix, but will post this here in case someone finds it faster than me.

![image](https://user-images.githubusercontent.com/6749277/120336179-18c4eb80-c2c0-11eb-99c1-58aaf19ca990.png)

**Comment by BitPhinix** [comment]
Hi @chasefarmer2808,

Thanks for raising this issue. Does this happen to you only in your dev setup or also on the hosted example? I currently can't reproduce this on my side. Something similar happend to me with slates internal normalization weak map and it was related to me using incorrect linked packages during development, I suspect something like this might be happening here as well

**Comment by chasefarmer2808** [comment]
Hello @BitPhinix 

Yes, I was able to reproduce in the hosted example.  I added the following SlateJS plugin:
```TypeScript
import { Operation } from "slate";
import { ReactEditor } from "slate-react";

export const ops = (editor: ReactEditor) => {
    const { apply } = editor;

    editor.apply = (operation: Operation) => {
        console.log(operation);
        apply(operation);
    }

    return editor;
}
```

And appended it to the SlateJS initialization in `Client.tsx`.  Then, I am able to see the `console.log` being hit twice.  This happens in one browser tab, and multiple browser tabs with the same room slug.

**Comment by BitPhinix** [comment]
I've investigated this a bit further but I'm unable to reproduce this behavior. If the operations are applied twice it should be fairly obvious since that would most likely result in an out-of-sync state between the different clients.

Could it be that the `console.log` statement is being called by multiple different clients on the same page? E.g. if you have 2 different clients it should be called twice for each modification you perform (once for the modification by slate and once when the change is synced to the other client)

**Comment by chasefarmer2808** [comment]
Thanks @BitPhinix.  I believe something is out of sync on my end.  Specifically when the library checks for `isLocal` and `isRemote`.  I've modified the `withYjs` function within `yjsEditor.ts` as such:
```typescript
e.onChange = () => {
    console.log('local?', YjsEditor.isLocal(e)); // <-- new
    console.log('remote?', YjsEditor.isRemote(e)); // <-- new
    if (!YjsEditor.isRemote(e)) {
      YjsEditor.applySlateOperations(e, e.operations);
    }

    onChange();
  };
```
After the first operation is applied, this `onChange` handler is called and it logs the following:
```
local? false
remote? false
```
Then, the second (exact same) operation is applied and this `onChange` handler gets hit a second time.  In this case, the following is logged:
```
local? false
remote? true
```
Is this correct?  And furthermore, is there any difference between `YjsEditor.isLocal()` and `!YjsEditor.isRemote()`, or vice versa?

**Comment by BitPhinix** [comment]
Hi @chasefarmer2808,

can you publish a repo with a reproducible example of this issue?

> is there any difference between YjsEditor.isLocal() and !YjsEditor.isRemote(), or vice versa?

Yes there is/was (isLocal was removed in the 3.0.0 release). `isLocal` was meant to keep track of operations we apply to the yjs document so we can distinguish between 'our' and external local modifications of the yjs document. `isRemote` is used to determine whether slate operations are caused by yjs events (that's why you can have both `isRemote` and `isLocal` false like in your example). This however was badly named so it's a good thing `isLocal` isn't a thing anymore and was replaced by a yjs transaction origin.

**Comment by chasefarmer2808** [comment]
I ran things with 3.0.0 and looks like the problem isn't happening anymore!

**Comment by BitPhinix** [comment]
Hmm interesting, still not sure what exactly was the issue here but good thing that it's solved now 👍

**Comment by chasefarmer2808** [comment]
Perhaps I spoke too soon.  Now it seems only remote operations are being applied twice.  Before it was local and remote.

**Comment by chasefarmer2808** [comment]
I will try and post a repo that can reproduce the issue.

**Comment by chasefarmer2808** [comment]
@BitPhinix Here is a repo where you can reproduce the issue.  You will need a yjs websocket server running on localhost:1234.  Run with `yarn start`.  Once the app opens in your browser, open the dev console.  Type some text after the "hello" and you will see only one console statement for each operation, as expected.  Next, open another tab or browser and go to localhost:3000.  Type some text in the new tab and observe in the first tab's console that operations are being logged twice.  Hope this helps!
https://github.com/chasefarmer2808/slate-yjs-test

**Comment by nemanja-tosic** [comment]
I see the duplicate operations in this example, but i can't figure out why they appear. If slate was trying to apply the same insert_text op twice, it would insert two characters, but instead it has the correct state as i type. It's as if the updates are applied to the wrong instance of the editor, a detached one, which would indicate a problem with the example rather than the library.

At any rate, i think this is a problem with the setup rather than slate-yjs, as we don't have this problem and use slate-yjs in production.

**Comment by e1himself** [comment]
I know this thread is massively old, but maybe this will be helpful for future visitors.

A typical cause for this class of problems is having two versions of the same package installed twice. This usually happens when a package is required with slightly different versions, and the package manager failing to properly deduplicate the dependency and thus leaving multiple copies of it in the tree.

The code that depends on local memory (like [WeakMap/WeakSet](https://github.com/BitPhinix/slate-yjs/blob/aa108641f44ca00559124cca8277a7c1e4354c00/packages/core/src/plugins/withYjs.ts#L25-L27)) or referential identity (like comparing things to [symbols](https://github.com/BitPhinix/slate-yjs/blob/aa108641f44ca00559124cca8277a7c1e4354c00/packages/core/src/plugins/withYjs.ts#L22-L23)) is build with the assumption that there is only one instance of this module, which may not always be the case.
