### ISSUE TITLE
Basic example from docs doesn't work

### ISSUE THREAD

**Issue by skokenes** [BitPhinix/slate-yjs#331]
Hi, I am trying to follow the documentation in order to migrate a legacy codebase up to the latest @slate-yjs. However, I can't seem to get even a simple demo working as I try to follow along with the docs.

See this Codesandbox, where the editor does not display the value loaded into the sharedType. Any feedback?
https://codesandbox.io/s/frosty-rubin-zi72yj?file=/src/App.js

**Comment by cmmartin** [comment]
FYI you can also fix it by removing `React.StrictMode`...

https://codesandbox.io/s/distracted-liskov-vp0jsf

This is because `React.StrictMode` [double invokes the useMemo functions](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects), which exposes the side effect mentioned by @BitPhinix

This seems to work fine on the current version of React, but is obviously likely to break in the future

**Comment by skokenes** [comment]
Thanks, that helped. I updated the sandbox with your suggestion, now it seems to work
