### ISSUE TITLE
Strange behavior offline + online editing

### ISSUE THREAD

**Issue by ovionlogis** [BitPhinix/slate-yjs#45]
Strange behavior when editing text online and offline at the same time
I ran this demo https://github.com/BitPhinix/slate-yjs-example
![Screen Recording 2020-10-13 at 17 09 04](https://user-images.githubusercontent.com/2921716/95848308-14bb7c00-0d78-11eb-80f7-cc22cbce4494.gif)

**Comment by BitPhinix** [comment]
Fixed in slate-yjs 0.1.3

**Comment by ovionlogis** [comment]
@BitPhinix I tested the demo again, the error repeats exactly the same

**Comment by BitPhinix** [comment]
Hmm weird, I'll recheck this again asap.

**Comment by Yshmeel** [comment]
This bug also occurs when you change selected mark at some part of text and refresh page, weird thing...

**Comment by BitPhinix** [comment]
I took a look at this today and the root cause is the way the `split_node` operation is translated.

Let's say we have 2 clients with the same state (a paragraph with the text hello world):
`{type: "paragraph", children: [{ text: "hello world"}]}`

Client 1 performs a split_node operation inside the paragraph with offset 5 this results in the following operations:
- remove text " world" from [0, 0]
- insert new text node containing " world" at [0, 1]

Client 2 simultaneously performs a split_node operation inside the paragraph with offset 6 this results in the following operations:
- remove text "world" from [0, 0]
- insert new text node containing "world" at [0, 1]

If the clients are now synced the remove text operations will be combined and both insert node operations will be applied resulting in both the "word" and " word" text nodes to be inserted. YJs can't know that the new nodes are a result of a split_node operations.

slate-collaborative has the exact same issue https://github.com/cudr/slate-collaborative/issues/29. I'll try to find a solution as soon as I find the time to or just port over the solution of slate-collaborative if they manage to solve it.

**Comment by BitPhinix** [comment]
Closing this issue because this is the intended behavior. For more details refer to: https://discuss.yjs.dev/t/modeling-slate-split-node-behavior-in-yjs/283/2

**Comment by big-camel** [comment]
This problem will cause PathRef to fail
